batch_size = 10
validation_split = .2
shuffle_dataset = False
random_seed = 42
dropout = False  # too much dropout?
learn_rate = .0006
lr_decay = 0.99
weight_decay = 1e-4
epochs = 8000
version = '0.05'
suppress_warnings = True
