batch_size = 1
validation_split = .2
shuffle_dataset = False
random_seed = 42
dropout = False  # too much dropout?
learn_rate = .002
lr_decay = 0.99
weight_decay = 1e-4
epochs = 1700
version = '0.01'
